#!/usr/bin/env python3
"""
Master Cleanup Script for QuantoniumOS

This script runs all cleanup scripts to thoroughly remove unnecessary files:
1. First runs the general cleanup to remove bytecode, cache, and temp files
2. Then runs the frontend/backend cleanup to remove duplicates and obsolete code
3. Finally generates a comprehensive cleanup report

Usage:
    python cleanup_master.py [--dry-run] [--verbose]

Options:
    --dry-run   Show what would be deleted without actually deleting
    --verbose   Show detailed information about each file processed
"""

import argparse
import datetime
import json
import os
import subprocess
import sys
from pathlib import Path


def run_script(script_path, args, verbose=False):
    """Run a cleanup script with the given arguments"""
    cmd = [sys.executable, script_path] + args
    if verbose:
        print(f"Running: {' '.join(cmd)}")

    try:
        result = subprocess.run(cmd, capture_output=True, text=True)
        if result.returncode != 0:
            print(f"Error running {script_path}:")
            print(result.stderr)
            return False

        print(result.stdout)
        return True
    except Exception as e:
        print(f"Exception running {script_path}: {e}")
        return False


def main():
    parser = argparse.ArgumentParser(description="Run all QuantoniumOS cleanup scripts")
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="Show what would be deleted without actually deleting",
    )
    parser.add_argument(
        "--verbose", action="store_true", help="Show detailed information"
    )
    args = parser.parse_args()

    script_args = []
    if args.dry_run:
        script_args.append("--dry-run")
    if args.verbose:
        script_args.append("--verbose")

    # Get the absolute paths to the scripts
    root_dir = Path(os.path.dirname(os.path.abspath(__file__)))

    script1_path = root_dir / "clean_unnecessary_files.py"
    script2_path = root_dir / "clean_frontend_backend.py"

    # Ensure the scripts exist
    if not script1_path.exists():
        print(f"Error: {script1_path} not found")
        return

    if not script2_path.exists():
        print(f"Error: {script2_path} not found")
        return

    # Run the scripts
    print("=" * 80)
    print("STEP 1: Running general cleanup of unnecessary files")
    print("=" * 80)
    success1 = run_script(script1_path, script_args, args.verbose)

    print("\n" + "=" * 80)
    print("STEP 2: Running frontend/backend cleanup")
    print("=" * 80)
    success2 = run_script(script2_path, script_args, args.verbose)

    # Generate a comprehensive report
    timestamp = datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S")

    report = {
        "timestamp": timestamp,
        "general_cleanup_success": success1,
        "frontend_backend_cleanup_success": success2,
        "dry_run": args.dry_run,
    }

    # Try to load any reports generated by the scripts
    try:
        if os.path.exists("frontend_backend_cleanup_report.json"):
            with open("frontend_backend_cleanup_report.json", "r") as f:
                frontend_backend_report = json.load(f)
                report["frontend_backend_details"] = frontend_backend_report
    except Exception as e:
        print(f"Error loading frontend/backend report: {e}")

    # Save the master report
    with open("MASTER_CLEANUP_REPORT.md", "w") as f:
        f.write(f"# QuantoniumOS Cleanup Report\n\n")
        f.write(f"**Generated:** {timestamp}\n\n")
        f.write(f"**Dry Run Mode:** {'Enabled' if args.dry_run else 'Disabled'}\n\n")

        f.write("## Cleanup Summary\n\n")
        f.write(f"1. General Cleanup: {'Completed' if success1 else 'Failed'}\n")
        f.write(
            f"2. Frontend/Backend Cleanup: {'Completed' if success2 else 'Failed'}\n\n"
        )

        if (
            "frontend_backend_details" in report
            and "stats" in report["frontend_backend_details"]
        ):
            stats = report["frontend_backend_details"]["stats"]
            f.write("## Files Found for Cleanup\n\n")
            f.write(f"- Duplicate Files: {stats.get('duplicate_count', 0)}\n")
            f.write(f"- Debug Files: {stats.get('debug_count', 0)}\n")
            f.write(f"- Obsolete Files: {stats.get('obsolete_count', 0)}\n")
            f.write(f"- Total Files: {stats.get('total_count', 0)}\n\n")

        f.write("## Next Steps\n\n")
        f.write("1. Review any error messages above\n")
        f.write("2. Run scripts individually if any issues occurred\n")
        f.write(
            "3. If this was a dry run, run again without --dry-run to perform the actual cleanup\n"
        )

    print("\n" + "=" * 80)
    print("CLEANUP PROCESS COMPLETE")
    print("=" * 80)
    print(f"Comprehensive report saved to: MASTER_CLEANUP_REPORT.md")

    if args.dry_run:
        print("\nThis was a DRY RUN. No files were actually deleted.")
        print("Run again without --dry-run to perform the actual cleanup.")


if __name__ == "__main__":
    main()
