#!/usr/bin/env python3
# QuantoniumOS Development Server
# Auto-generated by setup_local_env.py

import os
import sys
from pathlib import Path

# Load environment variables
if Path('.env').exists():
    from dotenv import load_dotenv
    load_dotenv()

# Add quantoniumos to path
sys.path.insert(0, 'quantoniumos')

try:
    from quantoniumos.main import main
    if __name__ == '__main__':
        print("Starting QuantoniumOS Development Server...")
        print("   Web: http://localhost:5000")
        print("   API: http://localhost:5000/docs")
        print("   Press Ctrl+C to stop")
        main()
except ImportError as e:
    print(f"Import error: {e}")
    print("   Make sure you're in the project root directory")
    sys.exit(1)
