// Generated by SandPiper(TM) 1.14-2022/10/10-beta-Pro from Redwood EDA, LLC.
// Redwood EDA, LLC does not claim intellectual property rights to this file and provides no warranty regarding its correctness or quality.


// For silencing unused signal messages.
`define BOGUS_USE(ignore)





//
// Signals declared top-level.
//

// For $block_counter.
logic [15:0] L0_block_counter_a0,
             L0_block_counter_a1;

// For $cfg_payload.
logic [127:0] L0_cfg_payload_a0,
              L0_cfg_payload_a1;

// For $cfg_ready_obs.
logic L0_cfg_ready_obs_a0;

// For $cfg_tile_id.
logic [6:0] L0_cfg_tile_id_a0;

// For $cfg_valid.
logic L0_cfg_valid_a0,
      L0_cfg_valid_a1;

// For $cycle.
logic [7:0] L0_cycle_a0,
            L0_cycle_a1;

// For $dma_payload.
logic [150:0] L0_dma_payload_a0,
              L0_dma_payload_a1;

// For $dma_ready_obs.
logic L0_dma_ready_obs_a0;

// For $dma_valid.
logic L0_dma_valid_a0,
      L0_dma_valid_a1;

// For $global_irq_done_obs.
logic L0_global_irq_done_obs_a0;

// For $global_irq_error_obs.
logic L0_global_irq_error_obs_a0;

// For $reset.
logic L0_reset_a0;

// For $rst_n.
logic L0_rst_n_a0;

// For $sample_seed.
logic [15:0] L0_sample_seed_a0,
             L0_sample_seed_a1;

// For $tile_busy_bitmap_obs.
logic [63:0] L0_tile_busy_bitmap_obs_a0;

// For $tile_done_bitmap_obs.
logic [63:0] L0_tile_done_bitmap_obs_a0;



   // Staging of $block_counter.
   always_ff @(posedge clk) L0_block_counter_a1[15:0] <= L0_block_counter_a0[15:0];

   // Staging of $cfg_payload.
   always_ff @(posedge clk) L0_cfg_payload_a1[127:0] <= L0_cfg_payload_a0[127:0];

   // Staging of $cfg_valid.
   always_ff @(posedge clk) L0_cfg_valid_a1 <= L0_cfg_valid_a0;

   // Staging of $cycle.
   always_ff @(posedge clk) L0_cycle_a1[7:0] <= L0_cycle_a0[7:0];

   // Staging of $dma_payload.
   always_ff @(posedge clk) L0_dma_payload_a1[150:0] <= L0_dma_payload_a0[150:0];

   // Staging of $dma_valid.
   always_ff @(posedge clk) L0_dma_valid_a1 <= L0_dma_valid_a0;

   // Staging of $sample_seed.
   always_ff @(posedge clk) L0_sample_seed_a1[15:0] <= L0_sample_seed_a0[15:0];


