// Auto-generated RFT test vectors
// DO NOT EDIT - Generated by rpu_test_vectors.py

localparam int NUM_RFT_TESTS = 15;
localparam int BLOCK_SIZE = 8;

// Test inputs (Q1.15 fixed-point)
logic signed [15:0] rft_test_input_real [NUM_RFT_TESTS][BLOCK_SIZE] = '{
  // Test 0: dc_signal
  '{16'sh28BA, 16'sh28BA, 16'sh28BA, 16'sh28BA, 16'sh28BA, 16'sh28BA, 16'sh28BA, 16'sh28BA},
  // Test 1: impulse
  '{16'sh7333, 16'sh0000, 16'sh0000, 16'sh0000, 16'sh0000, 16'sh0000, 16'sh0000, 16'sh0000},
  // Test 2: alternating
  '{16'sh28BA, 16'shD746, 16'sh28BA, 16'shD746, 16'sh28BA, 16'shD746, 16'sh28BA, 16'shD746},
  // Test 3: freq_k1
  '{16'sh28BA, 16'sh1CCC, 16'sh0000, 16'shE334, 16'shD746, 16'shE334, 16'sh0000, 16'sh1CCC},
  // Test 4: freq_k2
  '{16'sh28BA, 16'sh0000, 16'shD746, 16'sh0000, 16'sh28BA, 16'sh0000, 16'shD746, 16'sh0000},
  // Test 5: freq_k3
  '{16'sh28BA, 16'shE334, 16'sh0000, 16'sh1CCC, 16'shD746, 16'sh1CCC, 16'sh0000, 16'shE334},
  // Test 6: mixed_12
  '{16'sh357A, 16'sh1A78, 16'shEFF5, 16'shE588, 16'shEA9C, 16'shE588, 16'shEFF5, 16'sh1A78},
  // Test 7: ramp
  '{16'shC1C9, 16'shD390, 16'shE557, 16'shF71D, 16'sh08E3, 16'sh1AA9, 16'sh2C70, 16'sh3E37},
  // Test 8: chirp
  '{16'sh28BA, 16'sh25A1, 16'sh0000, 16'shDA5F, 16'sh28BA, 16'shDA5F, 16'sh0000, 16'sh25A1},
  // Test 9: zeros
  '{16'sh0000, 16'sh0000, 16'sh0000, 16'sh0000, 16'sh0000, 16'sh0000, 16'sh0000, 16'sh0000},
  // Test 10: max_positive
  '{16'sh28BA, 16'sh28BA, 16'sh28BA, 16'sh28BA, 16'sh28BA, 16'sh28BA, 16'sh28BA, 16'sh28BA},
  // Test 11: max_negative
  '{16'shD746, 16'shD746, 16'shD746, 16'shD746, 16'shD746, 16'shD746, 16'shD746, 16'shD746},
  // Test 12: random_1
  '{16'shF053, 16'sh0CFE, 16'sh26AD, 16'sh2AF2, 16'shEC60, 16'shF29C, 16'sh1F4D, 16'sh2D18},
  // Test 13: random_2
  '{16'sh1456, 16'sh1FE9, 16'shD847, 16'sh1584, 16'shD996, 16'sh275B, 16'shDCBB, 16'shE46F},
  // Test 14: random_3
  '{16'sh1FCC, 16'sh12E7, 16'sh03F4, 16'shE814, 16'sh2E24, 16'sh14A8, 16'sh2461, 16'sh18BF}
};

logic signed [15:0] rft_test_input_imag [NUM_RFT_TESTS][BLOCK_SIZE] = '{
  '{16'sh0000, 16'sh0000, 16'sh0000, 16'sh0000, 16'sh0000, 16'sh0000, 16'sh0000, 16'sh0000},
  '{16'sh0000, 16'sh0000, 16'sh0000, 16'sh0000, 16'sh0000, 16'sh0000, 16'sh0000, 16'sh0000},
  '{16'sh0000, 16'sh0000, 16'sh0000, 16'sh0000, 16'sh0000, 16'sh0000, 16'sh0000, 16'sh0000},
  '{16'sh0000, 16'sh1CCC, 16'sh28BA, 16'sh1CCC, 16'sh0000, 16'shE334, 16'shD746, 16'shE334},
  '{16'sh0000, 16'sh28BA, 16'sh0000, 16'shD746, 16'sh0000, 16'sh28BA, 16'sh0000, 16'shD746},
  '{16'sh0000, 16'sh1CCC, 16'shD746, 16'sh1CCC, 16'sh0000, 16'shE334, 16'sh28BA, 16'shE334},
  '{16'sh0000, 16'sh2A83, 16'sh256F, 16'sh0A6D, 16'sh0000, 16'shF593, 16'shDA91, 16'shD57D},
  '{16'sh0000, 16'sh0000, 16'sh0000, 16'sh0000, 16'sh0000, 16'sh0000, 16'sh0000, 16'sh0000},
  '{16'sh0000, 16'sh0F96, 16'sh28BA, 16'shF06A, 16'sh0000, 16'shF06A, 16'sh28BA, 16'sh0F96},
  '{16'sh0000, 16'sh0000, 16'sh0000, 16'sh0000, 16'sh0000, 16'sh0000, 16'sh0000, 16'sh0000},
  '{16'sh0000, 16'sh0000, 16'sh0000, 16'sh0000, 16'sh0000, 16'sh0000, 16'sh0000, 16'sh0000},
  '{16'sh0000, 16'sh0000, 16'sh0000, 16'sh0000, 16'sh0000, 16'sh0000, 16'sh0000, 16'sh0000},
  '{16'sh21C0, 16'shFCCB, 16'sh02A8, 16'shE289, 16'sh2DB5, 16'sh042E, 16'sh2575, 16'shEBEC},
  '{16'sh13B8, 16'sh155A, 16'shE41D, 16'sh1FB5, 16'sh18B4, 16'sh20A1, 16'sh0962, 16'sh1371},
  '{16'sh1447, 16'sh0354, 16'shD4CF, 16'sh201F, 16'sh2DC9, 16'shF0F1, 16'sh07F8, 16'sh2167}
};

// Expected outputs (Q1.15 fixed-point)
logic signed [15:0] rft_test_expected_real [NUM_RFT_TESTS][BLOCK_SIZE] = '{
  '{16'shD436, 16'sh403C, 16'shBD3D, 16'shD2C4, 16'shE7ED, 16'sh095B, 16'shF884, 16'shFFA0},
  '{16'shDAFD, 16'shD72C, 16'shD582, 16'shD5A9, 16'shD5A9, 16'shD582, 16'shD72C, 16'shDAFD},
  '{16'shFFA0, 16'shF884, 16'sh095B, 16'shE7ED, 16'shD2C4, 16'shBD3D, 16'sh403C, 16'shD436},
  '{16'sh013B, 16'shF0AC, 16'shEF14, 16'sh1416, 16'shEE27, 16'sh0899, 16'shDA1E, 16'shC1B4},
  '{16'sh1ECE, 16'shDF1A, 16'shE8EF, 16'shE48A, 16'shE48A, 16'shE8EF, 16'shDF1A, 16'sh1ECE},
  '{16'shC1B4, 16'shDA1E, 16'sh0899, 16'shEE27, 16'sh1416, 16'shEF14, 16'shF0AC, 16'sh013B},
  '{16'sh0D44, 16'shE4F3, 16'shE75C, 16'sh07A5, 16'shE4C7, 16'shFED2, 16'shD038, 16'shD2E0},
  '{16'shF456, 16'sh3039, 16'shF937, 16'sh56D8, 16'shFBD2, 16'shF887, 16'sh133A, 16'sh34B5},
  '{16'sh2DDD, 16'sh0C78, 16'shD571, 16'shF9BA, 16'shC829, 16'shF6CB, 16'shEF01, 16'shDADC},
  '{16'sh0000, 16'sh0000, 16'sh0000, 16'sh0000, 16'sh0000, 16'sh0000, 16'sh0000, 16'sh0000},
  '{16'shD436, 16'sh403C, 16'shBD3D, 16'shD2C4, 16'shE7ED, 16'sh095B, 16'shF884, 16'shFFA0},
  '{16'sh2BCA, 16'shBFC4, 16'sh42C3, 16'sh2D3C, 16'sh1813, 16'shF6A5, 16'sh077C, 16'sh0060},
  '{16'shDB62, 16'sh19A3, 16'shDF9D, 16'sh1189, 16'shFE99, 16'sh3733, 16'sh19E6, 16'shEFEC},
  '{16'shF789, 16'shE3F7, 16'sh02A1, 16'shE670, 16'sh3271, 16'sh04A6, 16'shBE8A, 16'sh0B7E},
  '{16'sh027F, 16'sh3002, 16'shDA88, 16'shF4E8, 16'shE076, 16'shD9E7, 16'shF581, 16'shF8AF}
};

logic signed [15:0] rft_test_expected_imag [NUM_RFT_TESTS][BLOCK_SIZE] = '{
  '{16'sh0000, 16'sh0000, 16'sh0000, 16'sh0000, 16'sh0000, 16'sh0000, 16'sh0000, 16'sh0000},
  '{16'sh0000, 16'sh0000, 16'sh0000, 16'sh0000, 16'sh0000, 16'sh0000, 16'sh0000, 16'sh0000},
  '{16'sh0000, 16'sh0000, 16'sh0000, 16'sh0000, 16'sh0000, 16'sh0000, 16'sh0000, 16'sh0000},
  '{16'sh0CFF, 16'shEBD9, 16'sh0D55, 16'shC9D9, 16'sh0200, 16'sh30C0, 16'sh0ECE, 16'shED49},
  '{16'sh120B, 16'sh2226, 16'sh1E44, 16'shE1D8, 16'sh1E28, 16'shE1BC, 16'shDDDA, 16'shEDF5},
  '{16'sh12B7, 16'shF132, 16'shCF40, 16'shFE00, 16'sh3627, 16'shF2AB, 16'sh1427, 16'shF301},
  '{16'sh130E, 16'shFAEE, 16'sh182D, 16'shC259, 16'sh0DB8, 16'sh20E2, 16'sh0027, 16'shE7B1},
  '{16'sh0000, 16'sh0000, 16'sh0000, 16'sh0000, 16'sh0000, 16'sh0000, 16'sh0000, 16'sh0000},
  '{16'shF6BF, 16'sh24BD, 16'shF647, 16'sh06AB, 16'shF224, 16'sh0416, 16'sh1888, 16'shD45D},
  '{16'sh0000, 16'sh0000, 16'sh0000, 16'sh0000, 16'sh0000, 16'sh0000, 16'sh0000, 16'sh0000},
  '{16'sh0000, 16'sh0000, 16'sh0000, 16'sh0000, 16'sh0000, 16'sh0000, 16'sh0000, 16'sh0000},
  '{16'sh0000, 16'sh0000, 16'sh0000, 16'sh0000, 16'sh0000, 16'sh0000, 16'sh0000, 16'sh0000},
  '{16'sh073D, 16'sh1491, 16'shEFCF, 16'shE921, 16'shECB0, 16'shC19F, 16'sh0F4A, 16'shF2A0},
  '{16'shF784, 16'sh0FF0, 16'shCEFF, 16'shF046, 16'sh0735, 16'shFA28, 16'shE561, 16'sh1F9C},
  '{16'sh1261, 16'shF5E8, 16'shBA4D, 16'sh0244, 16'shEE84, 16'shF9C4, 16'shFFF4, 16'sh2246}
};

string rft_test_names [NUM_RFT_TESTS] = '{
  "dc_signal",
  "impulse",
  "alternating",
  "freq_k1",
  "freq_k2",
  "freq_k3",
  "mixed_12",
  "ramp",
  "chirp",
  "zeros",
  "max_positive",
  "max_negative",
  "random_1",
  "random_2",
  "random_3"
};
