// Auto-generated RFT test vectors
// DO NOT EDIT - Generated by rpu_test_vectors.py

localparam int NUM_RFT_TESTS = 15;
localparam int BLOCK_SIZE = 8;

// Test inputs (Q1.15 fixed-point)
logic signed [15:0] rft_test_input_real [NUM_RFT_TESTS][BLOCK_SIZE] = '{
  // Test 0: dc_signal
  '{16'sh28BA, 16'sh28BA, 16'sh28BA, 16'sh28BA, 16'sh28BA, 16'sh28BA, 16'sh28BA, 16'sh28BA},
  // Test 1: impulse
  '{16'sh7333, 16'sh0000, 16'sh0000, 16'sh0000, 16'sh0000, 16'sh0000, 16'sh0000, 16'sh0000},
  // Test 2: alternating
  '{16'sh28BA, 16'shD746, 16'sh28BA, 16'shD746, 16'sh28BA, 16'shD746, 16'sh28BA, 16'shD746},
  // Test 3: freq_k1
  '{16'sh28BA, 16'sh1CCC, 16'sh0000, 16'shE334, 16'shD746, 16'shE334, 16'sh0000, 16'sh1CCC},
  // Test 4: freq_k2
  '{16'sh28BA, 16'sh0000, 16'shD746, 16'sh0000, 16'sh28BA, 16'sh0000, 16'shD746, 16'sh0000},
  // Test 5: freq_k3
  '{16'sh28BA, 16'shE334, 16'sh0000, 16'sh1CCC, 16'shD746, 16'sh1CCC, 16'sh0000, 16'shE334},
  // Test 6: mixed_12
  '{16'sh357A, 16'sh1A78, 16'shEFF5, 16'shE588, 16'shEA9C, 16'shE588, 16'shEFF5, 16'sh1A78},
  // Test 7: ramp
  '{16'shC1C9, 16'shD390, 16'shE557, 16'shF71D, 16'sh08E3, 16'sh1AA9, 16'sh2C70, 16'sh3E37},
  // Test 8: chirp
  '{16'sh28BA, 16'sh25A1, 16'sh0000, 16'shDA5F, 16'sh28BA, 16'shDA5F, 16'sh0000, 16'sh25A1},
  // Test 9: zeros
  '{16'sh0000, 16'sh0000, 16'sh0000, 16'sh0000, 16'sh0000, 16'sh0000, 16'sh0000, 16'sh0000},
  // Test 10: max_positive
  '{16'sh28BA, 16'sh28BA, 16'sh28BA, 16'sh28BA, 16'sh28BA, 16'sh28BA, 16'sh28BA, 16'sh28BA},
  // Test 11: max_negative
  '{16'shD746, 16'shD746, 16'shD746, 16'shD746, 16'shD746, 16'shD746, 16'shD746, 16'shD746},
  // Test 12: random_1
  '{16'shF053, 16'sh0CFE, 16'sh26AD, 16'sh2AF2, 16'shEC60, 16'shF29C, 16'sh1F4D, 16'sh2D18},
  // Test 13: random_2
  '{16'sh1456, 16'sh1FE9, 16'shD847, 16'sh1584, 16'shD996, 16'sh275B, 16'shDCBB, 16'shE46F},
  // Test 14: random_3
  '{16'sh1FCC, 16'sh12E7, 16'sh03F4, 16'shE814, 16'sh2E24, 16'sh14A8, 16'sh2461, 16'sh18BF}
};

logic signed [15:0] rft_test_input_imag [NUM_RFT_TESTS][BLOCK_SIZE] = '{
  '{16'sh0000, 16'sh0000, 16'sh0000, 16'sh0000, 16'sh0000, 16'sh0000, 16'sh0000, 16'sh0000},
  '{16'sh0000, 16'sh0000, 16'sh0000, 16'sh0000, 16'sh0000, 16'sh0000, 16'sh0000, 16'sh0000},
  '{16'sh0000, 16'sh0000, 16'sh0000, 16'sh0000, 16'sh0000, 16'sh0000, 16'sh0000, 16'sh0000},
  '{16'sh0000, 16'sh1CCC, 16'sh28BA, 16'sh1CCC, 16'sh0000, 16'shE334, 16'shD746, 16'shE334},
  '{16'sh0000, 16'sh28BA, 16'sh0000, 16'shD746, 16'sh0000, 16'sh28BA, 16'sh0000, 16'shD746},
  '{16'sh0000, 16'sh1CCC, 16'shD746, 16'sh1CCC, 16'sh0000, 16'shE334, 16'sh28BA, 16'shE334},
  '{16'sh0000, 16'sh2A83, 16'sh256F, 16'sh0A6D, 16'sh0000, 16'shF593, 16'shDA91, 16'shD57D},
  '{16'sh0000, 16'sh0000, 16'sh0000, 16'sh0000, 16'sh0000, 16'sh0000, 16'sh0000, 16'sh0000},
  '{16'sh0000, 16'sh0F96, 16'sh28BA, 16'shF06A, 16'sh0000, 16'shF06A, 16'sh28BA, 16'sh0F96},
  '{16'sh0000, 16'sh0000, 16'sh0000, 16'sh0000, 16'sh0000, 16'sh0000, 16'sh0000, 16'sh0000},
  '{16'sh0000, 16'sh0000, 16'sh0000, 16'sh0000, 16'sh0000, 16'sh0000, 16'sh0000, 16'sh0000},
  '{16'sh0000, 16'sh0000, 16'sh0000, 16'sh0000, 16'sh0000, 16'sh0000, 16'sh0000, 16'sh0000},
  '{16'sh21C0, 16'shFCCB, 16'sh02A8, 16'shE289, 16'sh2DB5, 16'sh042E, 16'sh2575, 16'shEBEC},
  '{16'sh13B8, 16'sh155A, 16'shE41D, 16'sh1FB5, 16'sh18B4, 16'sh20A1, 16'sh0962, 16'sh1371},
  '{16'sh1447, 16'sh0354, 16'shD4CF, 16'sh201F, 16'sh2DC9, 16'shF0F1, 16'sh07F8, 16'sh2167}
};

// Expected outputs (Q1.15 fixed-point)
logic signed [15:0] rft_test_expected_real [NUM_RFT_TESTS][BLOCK_SIZE] = '{
  '{16'sh7333, 16'sh0000, 16'sh0000, 16'sh0000, 16'sh0000, 16'sh0000, 16'sh0000, 16'sh0000},
  '{16'sh28BA, 16'shEEC9, 16'shD76E, 16'shDCBD, 16'shD7E5, 16'shE89E, 16'sh2755, 16'shE0D4},
  '{16'sh0000, 16'sh0000, 16'sh0000, 16'sh0000, 16'sh8E90, 16'sh0000, 16'sh0000, 16'sh0000},
  '{16'sh0000, 16'shCF4D, 16'sh0000, 16'sh0000, 16'sh0000, 16'sh0000, 16'sh0000, 16'sh0000},
  '{16'sh0000, 16'sh0000, 16'sh8D3E, 16'sh0000, 16'sh0000, 16'sh0000, 16'sh0000, 16'sh0000},
  '{16'sh0000, 16'sh0000, 16'sh0000, 16'sh9C42, 16'sh0000, 16'sh0000, 16'sh0000, 16'sh0000},
  '{16'sh0000, 16'shD33D, 16'shD2CC, 16'sh0000, 16'sh0000, 16'sh0000, 16'sh0000, 16'sh0000},
  '{16'sh0000, 16'sh41A0, 16'sh16D8, 16'sh108E, 16'sh18C1, 16'sh05E8, 16'shE133, 16'sh3A4C},
  '{16'sh1CCC, 16'shFE38, 16'shE5D5, 16'sh2860, 16'shDEA0, 16'sh08D7, 16'sh1456, 16'shD92B},
  '{16'sh0000, 16'sh0000, 16'sh0000, 16'sh0000, 16'sh0000, 16'sh0000, 16'sh0000, 16'sh0000},
  '{16'sh7333, 16'sh0000, 16'sh0000, 16'sh0000, 16'sh0000, 16'sh0000, 16'sh0000, 16'sh0000},
  '{16'sh8CCD, 16'sh0000, 16'sh0000, 16'sh0000, 16'sh0000, 16'sh0000, 16'sh0000, 16'sh0000},
  '{16'sh2B3F, 16'shF823, 16'sh0F56, 16'sh020A, 16'sh0816, 16'sh06E8, 16'shC64D, 16'shE9AA},
  '{16'shF627, 16'shF3B9, 16'shEB67, 16'shDA17, 16'sh3BFD, 16'sh00DB, 16'sh1F56, 16'shF042},
  '{16'sh3819, 16'sh151F, 16'sh0C08, 16'sh0194, 16'shE64C, 16'sh0A24, 16'sh3411, 16'sh0275}
};

logic signed [15:0] rft_test_expected_imag [NUM_RFT_TESTS][BLOCK_SIZE] = '{
  '{16'sh0000, 16'sh0000, 16'sh0000, 16'sh0000, 16'sh0000, 16'sh0000, 16'sh0000, 16'sh0000},
  '{16'sh0000, 16'shDB17, 16'sh038F, 16'sh1461, 16'sh0718, 16'shDEA7, 16'shF56E, 16'sh1A35},
  '{16'sh0000, 16'sh0000, 16'sh0000, 16'sh0000, 16'sh1410, 16'sh0000, 16'sh0000, 16'sh0000},
  '{16'sh0000, 16'sh979A, 16'sh0000, 16'sh0000, 16'sh0000, 16'sh0000, 16'sh0000, 16'sh0000},
  '{16'sh0000, 16'sh0000, 16'sh0A12, 16'sh0000, 16'sh0000, 16'sh0000, 16'sh0000, 16'sh0000},
  '{16'sh0000, 16'sh0000, 16'sh0000, 16'sh39A3, 16'sh0000, 16'sh0000, 16'sh0000, 16'sh0000},
  '{16'sh0000, 16'shA00B, 16'sh03F7, 16'sh0000, 16'sh0000, 16'sh0000, 16'sh0000, 16'sh0000},
  '{16'sh0000, 16'shFD21, 16'shE4C3, 16'shEA68, 16'shFBA0, 16'sh1A8F, 16'shEE40, 16'sh1E46},
  '{16'sh1CCC, 16'shD750, 16'sh1F35, 16'shFAAB, 16'shE8A9, 16'sh27C2, 16'shDCB6, 16'sh0C48},
  '{16'sh0000, 16'sh0000, 16'sh0000, 16'sh0000, 16'sh0000, 16'sh0000, 16'sh0000, 16'sh0000},
  '{16'sh0000, 16'sh0000, 16'sh0000, 16'sh0000, 16'sh0000, 16'sh0000, 16'sh0000, 16'sh0000},
  '{16'sh0000, 16'sh0000, 16'sh0000, 16'sh0000, 16'sh0000, 16'sh0000, 16'sh0000, 16'sh0000},
  '{16'sh191A, 16'sh0C76, 16'shD14E, 16'sh0844, 16'shC233, 16'sh0C11, 16'shFD8A, 16'sh0C53},
  '{16'sh2E55, 16'sh0CAA, 16'sh06E9, 16'sh1EFC, 16'sh11D4, 16'shE52B, 16'sh2AEC, 16'sh0BAF},
  '{16'sh1DED, 16'shFE0A, 16'shE8BF, 16'sh0DDC, 16'sh0CC9, 16'sh28B9, 16'sh2544, 16'sh22BC}
};

string rft_test_names [NUM_RFT_TESTS] = '{
  "dc_signal",
  "impulse",
  "alternating",
  "freq_k1",
  "freq_k2",
  "freq_k3",
  "mixed_12",
  "ramp",
  "chirp",
  "zeros",
  "max_positive",
  "max_negative",
  "random_1",
  "random_2",
  "random_3"
};
